### ISSUE TITLE
error 500 on Installation

### ISSUE THREAD

**Issue by CyliumDev** [utrustdev/utrust-for-prestashop#4]
Hello,
On installation we have an 500 error :
Attempted to call an undefined method named "autoExecute" of class "DbPDO".
in [modules/UTRUST/UTRUST.php] index.php/_profiler/open?_token=i7qUNvwNte7pgNvC8VBgdWFLIhLxNsJRpir296o9kQA?file=modules/UTRUST/UTRUST.php&line=140#line140) (line 140)

cordially

**Comment by bluegifts** [comment]
can't install either

**Comment by bluegifts** [comment]
this module doesn't work on 1.7 - says on description.
who still use presta 1.6?

**Comment by danielmcoelho** [comment]
Hello @CyliumDev and @bluegifts,

Like bluegifts mentioned, this module is for the legacy Prestashop 1.6 version. 
Since lately, we got a relevant increase on the requests of this module compatibility with version 1.7, we are working to get this updated.
Please watch the releases so you can get notified once it's out.
<img width="354" alt="Screenshot 2022-03-23 at 14 53 29" src="https://user-images.githubusercontent.com/1558992/159727921-396942e0-0cfe-4d38-b0e9-4873dc133e82.png">

Closing this for now.
